version: '1'
services: 
  web:
    build: .
    command: 'node index.js'
    ports:
     - "8080:8080"
  web:
    build: .
    command: 'node s3Upload.js'
    ports:
     - "27272:27272"
  web:
    build: .
    command: 'node notification.js'
    ports:
     - "27172:27172"
  redis:
    image: "redis:latest"